K: 
  - [4000.0,    0.0, 499.5]
  - [   0.0, 4000.0, 499.5]
  - [   0.0,    0.0,   1.0]
T: 
  - [ 0.,        -1.,          0.,          0.30591221]
  - [ 0.,         0.,         -1.,          0.30758971]
  - [ 1.,         0.,          0.,          2.99987025]
  - [ 0.,         0.,          0.,          1.        ]
