K: 
  - [3000.0,    0.0, 499.5]
  - [   0.0, 3000.0, 499.5]
  - [   0.0,    0.0,   1.0]
T: 
  - [ 0.,         -1.,          0.,          0.01458483]
  - [ 0.,          0.,         -1.,          0.12099323]
  - [ 1.,          0.,          0.,          2.00576733]
  - [ 0.,          0.,          0.,          1.        ]
